const dorks = [
  'intitle:"index of" "parent directory"',
  'intitle:"index of" "backup"',
  'intitle:"index of" "public"',
  'filetype:pdf "annual report"',
  'filetype:pdf "research"',
  'filetype:pdf "white paper"',
  'filetype:pdf "policy"',
  'filetype:pdf "guidelines"',
  'filetype:doc "proposal"',
  'filetype:docx "report"',
  'filetype:xls "budget"',
  'filetype:xlsx "budget"',
  'filetype:csv "dataset"',
  'filetype:csv "statistics"',
  'filetype:ppt "presentation"',
  'filetype:pptx "presentation"',
  'inurl:docs "documentation"',
  'inurl:docs "api"',
  'inurl:manual "user guide"',
  'inurl:help "faq"',
  'inurl:press "news"',
  'inurl:reports "report"',
  'inurl:downloads "download"',
  'inurl:resources "resource"',
  'inurl:publications "publication"',
  'intitle:"open data" dataset',
  'intitle:"data portal" dataset',
  'intitle:"research data" filetype:csv',
  'site:gov filetype:pdf "report"',
  'site:gov filetype:csv "data"',
  'site:edu filetype:pdf "thesis"',
  'site:edu filetype:pdf "dissertation"',
  'site:org filetype:pdf "annual report"',
  'site:org "impact report" filetype:pdf',
  'intitle:"project report" filetype:pdf',
  'intitle:"project brief" filetype:pdf',
  'intitle:"technical report" filetype:pdf',
  'intitle:"case study" filetype:pdf',
  'intitle:"press kit"',
  'intitle:"media kit"',
  'intitle:"resource library"',
  'intitle:"publication library"',
  'intitle:"policy brief" filetype:pdf',
  'intitle:"strategy" filetype:pdf',
  'intitle:"survey results" filetype:pdf',
  'intitle:"fact sheet" filetype:pdf',
  'intitle:"catalog" filetype:pdf',
  'intitle:"proceedings" filetype:pdf'
]

module.exports = dorks
